---
- name: Check OS Family
  set_fact:
    is_redhat: "{{ 'RedHat' in ansible_os_family }}"
    is_debian: "{{ 'Debian' in ansible_os_family }}"

- name: Install CrowdStrike on RedHat
  ansible.builtin.yum:
    name: "{{ crowdstrike_minio_url }}"
    state: present
  when: is_redhat
  become: true

- name: Install CrowdStrike on Debian
  ansible.builtin.apt:
    deb: "{{ crowdstrike_minio_url }}"
    state: present
  when: is_debian
  become: true

- name: Mark CrowdStrike as installed
  set_fact:
    crowdstrike_installed: true
  changed_when: true
